# TorchServe frontend parameters
minWorkers: 1
maxWorkers: 1
maxBatchDelay: 5000 # 单位是毫秒
responseTimeout: 5000 # 单位是秒
batchSize: 1
deviceType: "gpu"

handler:
    model_name: "meta-llama/Llama-2-7b-chat-hf"
    model_path: "model/models--meta-llama--Llama-2-7b-chat-hf/snapshots/08751db2aca9bf2f7f80d2e516117a53d7450235"
    max_length: 500
    max_new_tokens: 50
    manual_seed: 40