apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-service-1
  namespace: faas-scaler
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: 192.168.122.11:5000/helloworld-service:latest
        env:
        - name: TARGET
          value: "This is from helloworld-service-1"




    